[build]
  command = "npm run build"
  publish = "build"
  functions = "src/functions"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
